import { defineConfig } from 'astro/config';
import node from '@astrojs/node';

export default defineConfig({
  output: 'server',
  adapter: node({
    mode: 'standalone',
  }),
  redirects: {
    '/services': '/solutions/custom-software-automation/',
    '/shopify-migration-service': '/solutions/custom-software-automation/',
    '/shopify-development-agency-swishtag': '/solutions/custom-software-automation/',
    '/ui-ux-design-services': '/solutions/custom-software-automation/',
    '/shopify-agency-new-york': '/solutions/custom-software-automation/',
    '/shopify-theme-development': '/solutions/custom-software-automation/',
    '/shopify-ecommerce-solutions-for-promotional-product-distributors': '/shopify-company-store/',
    '/shopify-customer-migration': '/solutions/custom-software-automation/',
    '/rocket-gift-card-and-discount-shopify-app': '/shopify-apps-for-promotional-products/',
    '/platform/punchout': '/punchout-solutions/',
    '/product/punchout': '/punchout-solutions/',
    '/platform/purchase-orders': '/punchout-solutions/',
    '/platform/invoices': '/punchout-solutions/',
    '/platform/multi-store': '/platform/',
    '/platform/transactions': '/platform/',
    '/integrations': '/platform/',
    '/integrations/cxml': '/punchout-solutions/',
    '/integrations/jaggaer': '/punchout-solutions/',
    '/integrations/sap-ariba': '/punchout-solutions/',
    '/integrations/coupa': '/punchout-solutions/',
    '/integrations/oci': '/punchout-solutions/',
    '/integrations/oracle': '/punchout-solutions/',
    '/integrations/workday': '/punchout-solutions/',
    '/industries/promotional-print-uniforms': '/promotional-products-distributors/',
    '/industries/industrial-mro': '/industries/',
    '/industries/lab-scientific': '/industries/',
    '/project/pickpack': '/xecutor/',
    '/manufacturing-execution-system': '/xecutor/',
    '/project/mes': '/xecutor/',
  },
});
